services:
  app-dev:
    container_name: user-service-dev
    build:
      context: ./user-service
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    volumes:
      - ./user-service:/app
      - user_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    profiles:
      - dev
    command: npm run start:dev

  app-prod:
    container_name: user-service-prod
    build:
      context: ./user-service
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - "8080:3001"
    depends_on:
      - db
    profiles:
      - prod
    command: npm run start:prod

  db:
    image: postgres:15-alpine
    container_name: scoring-db
    env_file:
      - .env.development    # khi chạy prod bạn có thể override thành .env.production
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
  user_node_modules:
