FROM node:22-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


#production stage
FROM node:22-alpine as production

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY --from=build /app/dist ./dist

RUN npm run build

CMD ["npm","run","start:prod"]
